// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: rotom.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *StrSlice) Reset() {
	*x = StrSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrSlice) ProtoMessage() {}

func (x *StrSlice) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrSlice.ProtoReflect.Descriptor instead.
func (*StrSlice) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0}
}

func (x *StrSlice) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type UintSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []uint32 `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *UintSlice) Reset() {
	*x = UintSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UintSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UintSlice) ProtoMessage() {}

func (x *UintSlice) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UintSlice.ProtoReflect.Descriptor instead.
func (*UintSlice) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1}
}

func (x *UintSlice) GetData() []uint32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncMapEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K []string `protobuf:"bytes,1,rep,name=k,proto3" json:"k,omitempty"`
	V [][]byte `protobuf:"bytes,2,rep,name=v,proto3" json:"v,omitempty"`
}

func (x *SyncMapEntries) Reset() {
	*x = SyncMapEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncMapEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMapEntries) ProtoMessage() {}

func (x *SyncMapEntries) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMapEntries.ProtoReflect.Descriptor instead.
func (*SyncMapEntries) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{3}
}

func (x *SyncMapEntries) GetK() []string {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *SyncMapEntries) GetV() [][]byte {
	if x != nil {
		return x.V
	}
	return nil
}

var File_rotom_proto protoreflect.FileDescriptor

var file_rotom_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x55, 0x69, 0x6e, 0x74, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x0e, 0x53, 0x79, 0x6e,
	0x63, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x6b,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x01, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x01, 0x76, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x67, 0x7a, 0x6c, 0x75, 0x63, 0x61, 0x72, 0x69, 0x6f,
	0x2f, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rotom_proto_rawDescOnce sync.Once
	file_rotom_proto_rawDescData = file_rotom_proto_rawDesc
)

func file_rotom_proto_rawDescGZIP() []byte {
	file_rotom_proto_rawDescOnce.Do(func() {
		file_rotom_proto_rawDescData = protoimpl.X.CompressGZIP(file_rotom_proto_rawDescData)
	})
	return file_rotom_proto_rawDescData
}

var file_rotom_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rotom_proto_goTypes = []interface{}{
	(*StrSlice)(nil),       // 0: proto.StrSlice
	(*UintSlice)(nil),      // 1: proto.UintSlice
	(*Response)(nil),       // 2: proto.Response
	(*SyncMapEntries)(nil), // 3: proto.SyncMapEntries
}
var file_rotom_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rotom_proto_init() }
func file_rotom_proto_init() {
	if File_rotom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rotom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UintSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncMapEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rotom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rotom_proto_goTypes,
		DependencyIndexes: file_rotom_proto_depIdxs,
		MessageInfos:      file_rotom_proto_msgTypes,
	}.Build()
	File_rotom_proto = out.File
	file_rotom_proto_rawDesc = nil
	file_rotom_proto_goTypes = nil
	file_rotom_proto_depIdxs = nil
}
